[terminal]
# Run greetd on TTY1
vt = 1

[default_session]
# Use tuigreet as the greeter with session selector
command = "tuigreet --time --asterisks --sessions /usr/share/wayland-sessions --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot'"
user = "greetd"
