[terminal]
# Run greetd on TTY1
vt = 1

[default_session]
# Use tuigreet as the greeter, launching Niri directly
command = "tuigreet --time --asterisks --cmd /usr/bin/niri-tilefin-session --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot'"
user = "greetd"
